name: CTF
author: emilio27 and Yupsifuchs
version: 1.0
main: de.emilio.ctf.Main
api-version: 1.8

commands:
  hello:
    description: Greets you
    usage: /<command>
    permission: none
  setteams:
    description: Set the number of teams
    usage: /<command> <number of teams>
    permission: ctf.admin
